import type {Gen} from '@grogarden/gro/gen.js';
import {exists} from '@grogarden/gro/exists.js';
import {cwd} from 'node:process';
import {join, relative} from 'node:path';

import {create_atom_feed} from '$lib/feed.js';

// TODO extract to @fuz.dev/fuz_blog

export const gen: Gen = async ({origin_id}) => {
	// TODO parameterize
	const dir = cwd();
	const blog_dirname = 'blog';
	const blog_dir = join(dir, 'src/routes', blog_dirname); // TODO routes should be read from SvelteKit config

	const generated_by = relative(dir, origin_id);

	const {feed} = await import(join(blog_dir, 'feed.js')); // TODO BLOCK using this is a problem because it relies on `posts`

	// TODO BLOCK compare feed.items to the collected ones - can't use feed

	const found = await find_blog_items(blog_dir);

	const items = await Promise.all(
		found.map(async (item) => import(`$routes/${blog_dirname}/${item}/+page.svelte`)),
	);

	return [
		{
			filename: join(dir, 'static/blog/feed.xml'),
			content: create_atom_feed(feed),
		},
		{
			filename: join(blog_dir, 'posts.ts'),
			content: `
				// generated by ${generated_by}

				import type {FeedItem} from '$lib/feed.js';

				export const posts: FeedItem[] = [${items.map((item) => JSON.stringify(item.post)).join(',')}];

				// generated by ${generated_by}
			`,
		},
		...(await Promise.all(
			items.map(async (item, i) => {
				const post = item.post;
				const slug = post.url.split('/').at(-1)!; // TODO BLOCK maybe put the slug on the item and construct the URL
				const num = i + 1; // TODO BLOCK maybe put the `num` on the item (and think of a better name)
				return {
					filename: join(blog_dir, slug, '+page.svelte'),
					content: `
						<!-- generated by ${generated_by} -->

						<script lang="ts">
							import BlogPost${num} from '../${num}/+page.svelte';
						</script>

						<BlogPost${num} />

						<!-- generated by ${generated_by} -->
					`,
				};
			}),
		)),
	];
};

// const to_prerender_entries = (blog: Feed): string[] => {
// 	const entries = [];
// 	for (let index = 0; index < blog.items.length; index++) {
// 		const item = blog.items[index];
// 		const {pathname} = new URL(item.url);
// 		entries.push(pathname);
// 		// replace the last segment with the index
// 		for (let i = pathname.length - 1; i >= 0; i--) {
// 			if (pathname[i] === '/') {
// 				entries.push(pathname.substring(0, i + 1) + (1 + index));
// 				break;
// 			}
// 		}
// 	}
// 	return entries;
// };

const find_blog_items = async (blog_dir: string): Promise<number[]> => {
	const items: number[] = [];

	let i = 1;
	while (true) {
		// eslint-disable-next-line no-await-in-loop
		if (!(await exists(join(blog_dir, `${i}/+page.svelte`)))) {
			break;
		}
		items.push(i);
		i++;
	}

	return items;
};
