// generated by src/lib/projects.gen.ts

import type {ProjectInfo} from './project.ts';

export const projects: Array<ProjectInfo> = [
	{
		name: 'blog',
		title: '<a href="/blog">blog</a>',
		subtitle:
			'<a href="https://www.ryanatkn.com/blog/feed.xml" class="chip">feed.xml</a> <a href="https://github.com/ryanatkn/ryanatkn.com" class="chip">source</a>',
	},
	{
		name: 'github',
		title: '<a href="https://github.com/ryanatkn">github.com/ryanatkn</a>',
		description: 'my free and open source software',
	},
	{
		description: 'CSS framework and design system for semantic HTML',
		homepage: 'https://css.fuz.dev/',
		tagline: 'CSS with more utility',
		logo: 'logo.svg',
		logo_alt: 'a fuzzy tuft of green moss',
		glyph: '🪴',
		name: 'fuz_css',
		repo: '@fuzdev/fuz_css',
		title: '<a href="https://css.fuz.dev/">fuz_css</a>',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/fuz_css">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_css">npm</a>',
	},
	{
		description: '<a href="https://svelte.dev/">Svelte</a> UI library',
		homepage: 'https://ui.fuz.dev/',
		tagline: 'friendly user zystem',
		logo: 'logo.svg',
		logo_alt: 'a friendly brown spider facing you',
		glyph: '🧶',
		name: 'fuz_ui',
		repo: '@fuzdev/fuz_ui',
		title: '<a href="https://ui.fuz.dev/">fuz_ui</a>',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/fuz_ui">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_ui">npm</a>',
	},
	{
		description:
			'<a href="https://typescriptlang.org/">TypeScript</a> and <a href="https://svelte.dev/">Svelte</a> parser and formatter in <a href="https://www.rust-lang.org/">Rust</a>',
		homepage: 'https://tsv.fuz.dev/',
		name: 'tsv',
		repo: 'tsv',
		title: '<a href="https://tsv.fuz.dev/">tsv</a>',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/tsv">source</a> <a class="chip" href="https://tsv.fuz.dev/">playground</a>',
	},
	{
		description:
			'task runner and toolkit extending <a href="https://kit.svelte.dev/">SvelteKit</a>',
		homepage: 'https://gro.fuz.dev/',
		tagline: 'generate, run, optimize',
		logo: 'logo.svg',
		logo_alt: 'a pixelated green oak acorn with a glint of sun',
		glyph: '🌰',
		name: 'gro',
		repo: '@fuzdev/gro',
		title: '<a href="https://github.com/fuzdev/gro">Gro</a>',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/gro">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/gro">npm</a>',
	},
	{
		description:
			'static analysis for <a href="https://typescriptlang.org/">TypeScript</a> and <a href="https://svelte.dev/">Svelte</a>',
		homepage: 'https://svelte-docinfo.fuz.dev/',
		logo: 'logo.svg',
		logo_alt: 'a cyan scroll with curling ends',
		glyph: '📜',
		name: 'svelte-docinfo',
		repo: 'svelte-docinfo',
		title: '<a href="https://svelte-docinfo.fuz.dev/">svelte-docinfo</a>',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/svelte-docinfo">source</a> <a class="chip" href="https://www.npmjs.com/package/svelte-docinfo">npm</a>',
	},
	{
		description: 'utility belt for JS',
		homepage: 'https://util.fuz.dev/',
		tagline: 'ancient not extinct',
		logo: 'logo.svg',
		logo_alt: 'a green sauropod wearing a brown utility belt',
		glyph: '🦕',
		name: 'fuz_util',
		repo: '@fuzdev/fuz_util',
		title: '<a href="https://github.com/fuzdev/fuz_util">fuz_util</a>',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/fuz_util">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_util">npm</a>',
	},
	{
		description: 'fullstack app library with sessions, auth, and db',
		homepage: 'https://app.fuz.dev/',
		logo: 'logo.svg',
		logo_alt: 'a friendly teal spider facing you',
		glyph: '🗝',
		name: 'fuz_app',
		repo: '@fuzdev/fuz_app',
		title: '<a href="https://app.fuz.dev/">fuz_app</a>',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/fuz_app">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_app">npm</a>',
	},
	{
		description: 'software garage for power users and devs',
		homepage: 'https://www.zzz.software/',
		tagline: 'nice web things',
		logo: 'logo.svg',
		logo_alt: "three sleepy z's",
		glyph: '💤',
		name: 'zzz',
		repo: '@fuzdev/zzz',
		title: '<a href="https://www.zzz.software/">Zzz</a>',
		subtitle: '<a class="chip" href="https://github.com/fuzdev/zzz">source</a>',
	},
	{
		description: 'a blog and YouTube channel for web and native dev',
		homepage: 'https://www.webdevladder.net/',
		tagline: 'up ↗',
		logo: 'logo.svg',
		logo_alt: 'a spider web between two rungs of a ladder',
		glyph: '🪜',
		name: 'webdevladder.net',
		repo: 'webdevladder.net',
		title: '<a href="https://www.webdevladder.net/">webdevladder.net</a>',
		subtitle:
			'<a class="chip" href="https://www.youtube.com/@webdevladder">channel</a> <a class="chip" href="https://www.youtube.com/@webdevladder_vods">vods</a> <a class="chip" href="https://github.com/ryanatkn/webdevladder.net">source</a>',
	},
	{
		name: 'cosmicplayground',
		repo: '@ryanatkn/cosmicplayground',
		homepage: 'https://www.cosmicplayground.org/',
		title: '<a href="https://www.cosmicplayground.org">cosmicplayground.org</a>',
		subtitle: '<a class="chip" href="https://github.com/ryanatkn/cosmicplayground">source</a>',
		description: 'hobby project for fun and learning',
		tagline: 'tools and toys for expanding minds',
		logo_style: 'border-radius: 50%',
		logo: 'favicon.png',
	},
];
