// generated by src/lib/blog.gen.ts

import type {BlogFeed} from '$lib/blog.js';

export const feed: BlogFeed = {
	title: 'Ryan Atkinson',
	id: 'https://www.ryanatkn.com/',
	home_page_url: 'https://www.ryanatkn.com/',
	description: 'blog of a web developer building free and open source software',
	icon: 'https://www.ryanatkn.com/favicon.png',
	favicon: 'https://www.ryanatkn.com/favicon.png',
	author: {name: 'Ryan Atkinson', url: 'https://www.ryanatkn.com/', email: 'mail@ryanatkn.com'},
	atom: {feed_url: 'https://www.ryanatkn.com/blog/feed.xml'},
	items: [
		{
			id: 'https://www.ryanatkn.com/blog/1',
			url: 'https://www.ryanatkn.com/blog/making-free-and-open-source-web-community-software',
			blog_post_id: 1,
			title: 'Building free and open source web community software',
			slug: 'making-free-and-open-source-web-community-software',
			date_published: '2022-05-13T01:42:23.000Z',
			date_modified: '2023-07-23T17:12:50.674Z',
			summary:
				'I discuss my work on open source community software called feltjs, giving a brief overview of the design and technology choices, and announcing our newsletter and podcast.',
			tags: ['web', 'technology', 'social', 'software', 'open source', 'community', 'FOSS'],
		},
		{
			id: 'https://www.ryanatkn.com/blog/2',
			url: 'https://www.ryanatkn.com/blog/modeling-virtual-social-spaces-in-this-house-we-post-cat-pics-on-saturday',
			blog_post_id: 2,
			title: 'Modeling virtual social spaces: in this house we post cat pics on Saturday',
			slug: 'modeling-virtual-social-spaces-in-this-house-we-post-cat-pics-on-saturday',
			date_published: '2023-01-22T21:44:17.224Z',
			date_modified: '2023-01-28T17:20:51.259Z',
			summary:
				'Proposing a model for one of the central aspects of online communities: the virtual social space.',
			tags: ['web', 'community', 'social media', 'design', 'technology', 'software'],
			comments: {url: 'https://hci.social/@ryanatkn/109768104377997044', type: 'mastodon'},
		},
	],
};

// generated by src/lib/blog.gen.ts
