// generated by src/lib/blog.gen.ts

import type {BlogFeed} from '@fuzdev/fuz_blog/blog.js';

export const feed: BlogFeed = {
	title: "Ryan Atkinson's blog",
	id: 'https://www.ryanatkn.com/',
	home_page_url: 'https://www.ryanatkn.com/',
	description: 'blog of a software developer building free and open source tools and toys',
	icon: 'https://www.ryanatkn.com/favicon.png',
	favicon: 'https://www.ryanatkn.com/favicon.png',
	author: {name: 'Ryan Atkinson', url: 'https://www.ryanatkn.com/', email: 'mail@ryanatkn.com'},
	atom: {feed_url: 'https://www.ryanatkn.com/blog/feed.xml'},
	items: [
		{
			id: 'https://www.ryanatkn.com/blog/1',
			url: 'https://www.ryanatkn.com/blog/modeling-virtual-social-spaces-in-this-house-we-post-cat-pics-on-saturday',
			blog_post_id: 1,
			title: 'Modeling virtual social spaces: in this house we post cat pics on Saturday',
			slug: 'modeling-virtual-social-spaces-in-this-house-we-post-cat-pics-on-saturday',
			date_published: '2023-01-22T21:44:17.224Z',
			date_modified: '2023-01-28T17:20:51.259Z',
			summary:
				'Proposing a model for one of the central aspects of online communities: the virtual social space.',
			tags: ['web', 'community', 'social media', 'design', 'technology', 'software'],
			comments: {url: 'https://hci.social/@ryanatkn/109768104377997044', type: 'mastodon'},
		},
	],
};

// generated by src/lib/blog.gen.ts
