// generated by src/lib/blog.gen.ts

import type {BlogPostItem} from '$lib/blog.js';

export const posts: BlogPostItem[] = [
	{
		id: 'https://www.ryanatkn.com/blog/1',
		url: 'https://www.ryanatkn.com/blog/making-free-and-open-source-web-community-software',
		blog_post_id: 1,
		title: 'Building free and open source web community software',
		slug: 'making-free-and-open-source-web-community-software',
		date_published: '2022-05-13T01:42:23.000Z',
		date_modified: '2023-07-23T17:12:50.674Z',
		summary:
			'I discuss my work on open source community software called feltjs, giving a brief overview of the design and technology choices, and announcing our newsletter and podcast.',
		tags: ['web', 'technology', 'social', 'software', 'open source', 'community', 'FOSS'],
	},
	{
		id: 'https://www.ryanatkn.com/blog/2',
		url: 'https://www.ryanatkn.com/blog/modeling-virtual-social-spaces-in-this-house-we-post-cat-pics-on-saturday',
		blog_post_id: 2,
		title: 'Modeling virtual social spaces: in this house we post cat pics on Saturday',
		slug: 'modeling-virtual-social-spaces-in-this-house-we-post-cat-pics-on-saturday',
		date_published: '2023-01-22T21:44:17.224Z',
		date_modified: '2023-01-28T17:20:51.259Z',
		summary:
			'Proposing a model for one of the central aspects of online communities: the virtual social space.',
		tags: ['web', 'community', 'social media', 'design', 'technology', 'software'],
	},
	{
		id: 'https://www.ryanatkn.com/blog/3',
		url: 'https://www.ryanatkn.com/blog/modeling-virtual-social-spaces-the-roles-of-steward-operator-and-builder',
		blog_post_id: 3,
		title: 'Modeling virtual social spaces: the roles of steward, operator, and builder',
		slug: 'modeling-virtual-social-spaces-the-roles-of-steward-operator-and-builder',
		date_published: '2023-07-24T01:50:35.017Z',
		date_modified: '2023-07-24T01:50:35.017Z',
		summary:
			'I describe how I like the builder role when working on social spaces, but less so the steward and operator roles and the responsibilities they carry. Also, how I implemented allowlisted Mastodon comments on my static blog with TypeScript, Svelte, and SvelteKit, but an API limitation compromised my desire to steward the comments.',
		tags: [
			'web',
			'personal',
			'builders',
			'stewards',
			'social spaces',
			'blog comments',
			'Mastodon',
			'ActivityPub',
			'ActivityStreams',
			'Fediverse',
			'design',
			'technology',
			'software',
		],
		comments: {type: 'mastodon', url: 'https://mastodon.ryanatkn.com/@ryanatkn/110843291155970959'},
	},
];

// generated by src/lib/blog.gen.ts
