// generated by library.gen.ts !! do not edit directly or risk lost data

import type {LibraryJson} from '@fuzdev/fuz_util/library_json.js';

export const library_json: LibraryJson = {
	package_json: {
		name: 'ryanatkn.com',
		version: '0.0.1',
		description: "@ryanatkn's homepage and blog",
		motto: 'all ways a wip',
		glyph: '🪶',
		logo: 'favicon.png',
		logo_alt: 'a textured green nature circle with a void center',
		public: true,
		license: 'MIT',
		homepage: 'https://www.ryanatkn.com/',
		author: {
			name: 'Ryan Atkinson',
			email: 'mail@ryanatkn.com',
			url: 'https://www.ryanatkn.com/',
		},
		repository: {
			type: 'git',
			url: 'git+https://github.com/ryanatkn/ryanatkn.com.git',
		},
		bugs: 'https://github.com/ryanatkn/ryanatkn.com/issues',
		funding: 'https://www.ryanatkn.com/funding',
		scripts: {
			start: 'gro dev',
			dev: 'gro dev',
			build: 'gro build',
			check: 'gro check',
			test: 'gro test',
			preview: 'vite preview',
			deploy: 'gro deploy',
		},
		type: 'module',
		engines: {
			node: '>=22.15',
		},
		devDependencies: {
			'@prettier/plugin-xml': '^3.4.2',
			'@fuzdev/fuz_util': '^0.41.1',
			'@ryanatkn/eslint-config': '^0.9.0',
			'@fuzdev/fuz_ui': '^0.168.0',
			'@fuzdev/fuz_blog': '^0.19.0',
			'@fuzdev/fuz_gitops': '^0.56.0',
			'@fuzdev/fuz_mastodon': '^0.36.0',
			'@ryanatkn/gro': '^0.180.0',
			'@fuzdev/fuz_css': '^0.39.0',
			'@sveltejs/adapter-static': '^3.0.10',
			'@sveltejs/kit': '^2.49.0',
			'@sveltejs/vite-plugin-svelte': '^6.2.1',
			'@types/node': '^24.10.1',
			'date-fns': '^4.1.0',
			eslint: '^9.39.1',
			'eslint-plugin-svelte': '^3.13.0',
			'esm-env': '^1.2.2',
			prettier: '^3.6.2',
			'prettier-plugin-svelte': '^3.4.0',
			svelte: '^5.45.2',
			'svelte-check': '^4.3.4',
			tslib: '^2.8.1',
			typescript: '^5.9.3',
			'typescript-eslint': '^8.48.0',
			vitest: '^4.0.14',
			zod: '^4.1.13',
		},
		prettier: {
			plugins: ['prettier-plugin-svelte', '@prettier/plugin-xml'],
			useTabs: true,
			printWidth: 100,
			singleQuote: true,
			bracketSpacing: false,
			overrides: [
				{
					files: 'package.json',
					options: {
						useTabs: false,
					},
				},
			],
		},
		sideEffects: ['**/*.css'],
		files: ['dist'],
	},
	source_json: {
		name: 'ryanatkn.com',
		version: '0.0.1',
		modules: [
			{
				path: 'blog.gen.ts',
				declarations: [],
			},
			{
				path: 'gitops_analyze.task.ts',
				declarations: [],
			},
			{
				path: 'gitops_plan.task.ts',
				declarations: [],
			},
			{
				path: 'gitops_publish.task.ts',
				declarations: [],
			},
			{
				path: 'gitops_sync.task.ts',
				declarations: [],
			},
			{
				path: 'gitops_validate.task.ts',
				declarations: [],
			},
			{
				path: 'post.task.ts',
				declarations: [],
			},
		],
	},
	name: 'ryanatkn.com',
	repo_name: 'ryanatkn.com',
	repo_url: 'https://github.com/ryanatkn/ryanatkn.com',
	owner_name: 'ryanatkn',
	homepage_url: 'https://www.ryanatkn.com/',
	logo_url: 'https://www.ryanatkn.com/favicon.png',
	logo_alt: 'a textured green nature circle with a void center',
	npm_url: null,
	changelog_url: null,
	published: false,
};

// generated by library.gen.ts !! do not edit directly or risk lost data
