// generated by src/routes/projects.gen.ts

import type {Project_Info} from '$routes/project.js';

export const projects: Array<Project_Info> = [
	{
		name: 'blog',
		title: '<a href="/blog">blog</a>',
		subtitle:
			'<a href="https://www.ryanatkn.com/blog/feed.xml" class="chip">feed.xml</a> <a href="https://github.com/ryanatkn/ryanatkn.com" class="chip">source</a>',
	},
	{
		name: 'github',
		title: '<a href="https://github.com/ryanatkn">github.com/ryanatkn</a>',
		description: 'my free and open source software',
	},
	{
		name: 'zzz',
		repo: '@ryanatkn/zzz',
		title: '<a href="https://www.zzzbot.dev/">Zzz</a>',
		description: 'webtool',
		subtitle: '<a class="chip" href="https://github.com/ryanatkn/zzz">source</a>',
		motto: 'bot control web',
		glyph: '💤',
		logo: 'logo.svg',
		logo_alt: "three sleepy z's",
	},
	{
		description:
			'a YouTube channel and blog for realworld webdev with <a href="https://typescriptlang.org/">TypeScript</a> and <a href="https://svelte.dev/">Svelte</a>',
		homepage: 'https://www.webdevladder.net/',
		motto: 'up ↗',
		logo: 'logo.svg',
		logo_alt: 'a spider web between two rungs of a ladder',
		glyph: '🪜',
		name: 'webdevladder.net',
		repo: 'webdevladder.net',
		title: '<a href="https://www.webdevladder.net/">webdevladder.net</a>',
		subtitle:
			'<a class="chip" href="https://www.youtube.com/@webdevladder">channel</a> <a class="chip" href="https://www.youtube.com/@webdevladder_vods">vods</a> <a class="chip" href="https://github.com/ryanatkn/webdevladder.net">source</a>',
	},
	{
		description: 'CSS framework and design system',
		homepage: 'https://moss.ryanatkn.com/',
		motto: 'magical organic stylesheets',
		logo: 'logo.svg',
		logo_alt: 'a fuzzy tuft of green moss',
		glyph: '🌿',
		name: 'moss',
		repo: '@ryanatkn/moss',
		title: '<a href="https://moss.ryanatkn.com/">Moss</a>',
		subtitle:
			'<a class="chip" href="https://github.com/ryanatkn/moss">source</a> <a class="chip" href="https://www.npmjs.com/package/@ryanatkn/moss">npm</a>',
	},
	{
		description: '<a href="https://svelte.dev/">Svelte</a> UI library',
		homepage: 'https://www.fuz.dev/',
		motto: 'friendly user zystem',
		logo: 'logo.svg',
		logo_alt: 'a friendly brown spider facing you',
		glyph: '🧶',
		name: 'fuz',
		repo: '@ryanatkn/fuz',
		title: '<a href="https://www.fuz.dev/">Fuz</a>',
		subtitle:
			'<a class="chip" href="https://github.com/ryanatkn/fuz">source</a> <a class="chip" href="https://www.npmjs.com/package/@ryanatkn/fuz">npm</a>',
	},
	{
		description:
			'task runner and toolkit extending <a href="https://kit.svelte.dev/">SvelteKit</a>',
		homepage: 'https://gro.ryanatkn.com/',
		motto: 'generate, run, optimize',
		logo: 'logo.svg',
		logo_alt: 'a pixelated green oak acorn with a glint of sun',
		glyph: '🌰',
		name: 'gro',
		repo: '@ryanatkn/gro',
		title: '<a href="https://github.com/ryanatkn/gro">Gro</a>',
		subtitle:
			'<a class="chip" href="https://github.com/ryanatkn/gro">source</a> <a class="chip" href="https://www.npmjs.com/package/@ryanatkn/gro">npm</a>',
	},
	{
		description: 'utility belt for JS',
		homepage: 'https://belt.ryanatkn.com/',
		motto: 'ancient not extinct',
		logo: 'logo.svg',
		logo_alt: 'a green sauropod wearing a brown utility belt',
		glyph: '🦕',
		name: 'belt',
		repo: '@ryanatkn/belt',
		title: '<a href="https://github.com/ryanatkn/belt">Belt</a>',
		subtitle:
			'<a class="chip" href="https://github.com/ryanatkn/belt">source</a> <a class="chip" href="https://www.npmjs.com/package/@ryanatkn/belt">npm</a>',
	},
	{
		description: 'hobby project for fun and learning',
		homepage: 'https://www.cosmicplayground.org/',
		motto: 'tools and toys for expanding minds',
		logo: 'favicon.png',
		name: 'cosmicplayground',
		repo: '@ryanatkn/cosmicplayground',
		title: '<a href="https://www.cosmicplayground.org">cosmicplayground.org</a>',
		subtitle: '<a class="chip" href="https://github.com/ryanatkn/cosmicplayground">source</a>',
		logo_style: 'border-radius: 50%',
	},
];
