// generated by src/routes/projects.gen.ts

import type {ProjectInfo} from '$routes/project.ts';

export const projects: Array<ProjectInfo> = [
	{
		name: 'blog',
		title: '<a href="/blog">blog</a>',
		subtitle:
			'<a href="https://www.ryanatkn.com/blog/feed.xml" class="chip">feed.xml</a> <a href="https://github.com/ryanatkn/ryanatkn.com" class="chip">source</a>',
	},
	{
		name: 'github',
		title: '<a href="https://github.com/ryanatkn">github.com/ryanatkn</a>',
		description: 'my free and open source software',
	},
	{
		name: 'zzz',
		repo: '@fuzdev/zzz',
		title: '<a href="https://www.zzz.software/">Zzz</a>',
		description: 'fullstack toolkit for adaptive web environments',
		subtitle: '<a class="chip" href="https://github.com/fuzdev/zzz">source</a>',
		motto: 'nice web things',
		glyph: '💤',
		logo: 'logo.svg',
		logo_alt: "three sleepy z's",
	},
	{
		name: 'webdevladder.net',
		repo: 'webdevladder.net',
		title: '<a href="https://www.webdevladder.net/">webdevladder.net</a>',
		description:
			'a YouTube channel and blog for realworld webdev with <a href="https://typescriptlang.org/">TypeScript</a> and <a href="https://svelte.dev/">Svelte</a>',
		subtitle:
			'<a class="chip" href="https://www.youtube.com/@webdevladder">channel</a> <a class="chip" href="https://www.youtube.com/@webdevladder_vods">vods</a> <a class="chip" href="https://github.com/ryanatkn/webdevladder.net">source</a>',
	},
	{
		name: 'fuz_css',
		repo: '@fuzdev/fuz_css',
		title: '<a href="https://css.fuz.dev/">fuz_css</a>',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/fuz_css">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_css">npm</a>',
	},
	{
		name: 'fuz',
		repo: '@fuzdev/fuz_ui',
		title: '<a href="https://ui.fuz.dev/">fuz_ui</a>',
		description: '<a href="https://svelte.dev/">Svelte</a> UI library',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/fuz_ui">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_ui">npm</a>',
	},
	{
		name: 'gro',
		repo: '@ryanatkn/gro',
		title: '<a href="https://github.com/ryanatkn/gro">Gro</a>',
		description:
			'task runner and toolkit extending <a href="https://kit.svelte.dev/">SvelteKit</a>',
		subtitle:
			'<a class="chip" href="https://github.com/ryanatkn/gro">source</a> <a class="chip" href="https://www.npmjs.com/package/@ryanatkn/gro">npm</a>',
	},
	{
		name: 'fuz_util',
		repo: '@fuzdev/fuz_util',
		title: '<a href="https://github.com/fuzdev/fuz_util">fuz_util</a>',
		description: 'utility belt for JS',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/fuz_util">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_util">npm</a>',
	},
	{
		name: 'cosmicplayground',
		repo: '@ryanatkn/cosmicplayground',
		title: '<a href="https://www.cosmicplayground.org">cosmicplayground.org</a>',
		subtitle: '<a class="chip" href="https://github.com/ryanatkn/cosmicplayground">source</a>',
		description: 'hobby project for fun and learning',
		motto: 'tools and toys for expanding minds',
		logo_style: 'border-radius: 50%',
		logo: 'favicon.png',
	},
];
