import type {Gen} from '@ryanatkn/gro';
import {resolve} from '$app/paths';

import type {ProjectInfo} from '$routes/project.ts';
import {repos_json} from '$routes/repos.ts';

/**
 * Generating `projects.ts` to avoid loading the whole `repos.ts` on the homepage.
 */
export const gen: Gen = ({origin_path}) => {
	return `
		// generated by ${origin_path}

    import type {ProjectInfo} from '$routes/project.ts';
    
    export const projects: Array<ProjectInfo> = ${JSON.stringify(projects)};
  `;
};

interface ProjectMetadata {
	name: string;
	/**
	 * Allows HTML.
	 */
	description?: string;
	motto?: string; // TODO @many this is a hack because cosmicplayground hasn't been deployed
	glyph?: string; // TODO @many hack for zzz, fix after adding to gitops
	repo?: string;
	/**
	 * Allows HTML.
	 */
	title: string;
	/**
	 * Allows HTML.
	 */
	subtitle?: string;
	logo?: string; // TODO @many this is a hack because cosmicplayground hasn't been deployed
	logo_alt?: string; // TODO @many hack for zzz, fix after adding to gitops
	logo_style?: string;
}

// TODO description, motto, icon, icon_alt, glyph
const projects_metadata: Array<ProjectMetadata> = [
	{
		name: 'blog',
		title: `<a href="${resolve('/blog')}">blog</a>`,
		subtitle:
			'<a href="https://www.ryanatkn.com/blog/feed.xml" class="chip">feed.xml</a> <a href="https://github.com/ryanatkn/ryanatkn.com" class="chip">source</a>',
	},
	{
		name: 'github',
		title: '<a href="https://github.com/ryanatkn">github.com/ryanatkn</a>',
		description: 'my free and open source software',
	},
	// {
	// 	name: 'spiderspace',
	//  repo: '@ryanatkn/spiderspace.org',
	// 	title: '<a href="https://www.spiderspace.org/">spiderspace.org</a>',
	// 	description: 'community website with a YouTube channel about building it',
	// 	subtitle: `<a class="chip" href="https://www.youtube.com/@spiderspace_8000">YouTube</a> <a class="chip" href="https://github.com/ryanatkn/spiderspace.org">source</a>`,
	// },
	{
		// TODO @many hack for zzz, fix after adding to gitops
		name: 'zzz',
		repo: '@fuzdev/zzz',
		title: '<a href="https://www.zzz.software/">Zzz</a>',
		description: 'fullstack toolkit for adaptive web environments',
		subtitle: `<a class="chip" href="https://github.com/fuzdev/zzz">source</a>`, // TODO publish zzz - <a class="chip" href="https://www.npmjs.com/package/@fuzdev/zzz">npm</a>
		// TODO @many hack for zzz, fix after adding to gitops
		motto: 'nice web things',
		glyph: '💤',
		logo: 'logo.svg',
		logo_alt: "three sleepy z's",
	},
	{
		name: 'webdevladder.net',
		repo: 'webdevladder.net',
		title: '<a href="https://www.webdevladder.net/">webdevladder.net</a>',
		description:
			'a YouTube channel and blog for realworld webdev with <a href="https://typescriptlang.org/">TypeScript</a> and <a href="https://svelte.dev/">Svelte</a>',
		subtitle: `<a class="chip" href="https://www.youtube.com/@webdevladder">channel</a> <a class="chip" href="https://www.youtube.com/@webdevladder_vods">vods</a> <a class="chip" href="https://github.com/ryanatkn/webdevladder.net">source</a>`,
	},
	{
		name: 'fuz_css',
		repo: '@fuzdev/fuz_css',
		title: '<a href="https://css.fuz.dev/">Fuz CSS</a>',
		subtitle: `<a class="chip" href="https://github.com/fuzdev/fuz_css">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_css">npm</a>`,
	},
	{
		name: 'fuz',
		repo: '@fuzdev/fuz_ui',
		title: '<a href="https://ui.fuz.dev/">Fuz UI</a>',
		description: '<a href="https://svelte.dev/">Svelte</a> UI library',
		subtitle: `<a class="chip" href="https://github.com/fuzdev/fuz_ui">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_ui">npm</a>`,
	},
	{
		name: 'gro',
		repo: '@ryanatkn/gro',
		title: '<a href="https://github.com/ryanatkn/gro">Gro</a>',
		description:
			'task runner and toolkit extending <a href="https://kit.svelte.dev/">SvelteKit</a>',
		subtitle: `<a class="chip" href="https://github.com/ryanatkn/gro">source</a> <a class="chip" href="https://www.npmjs.com/package/@ryanatkn/gro">npm</a>`,
	},
	{
		name: 'fuz_util',
		repo: '@fuzdev/fuz_util',
		title: '<a href="https://github.com/fuzdev/fuz_util">fuz_util</a>',
		description: 'utility belt for JS',
		subtitle:
			'<a class="chip" href="https://github.com/fuzdev/fuz_util">source</a> <a class="chip" href="https://www.npmjs.com/package/@fuzdev/fuz_util">npm</a>',
	},
	{
		name: 'cosmicplayground',
		repo: '@ryanatkn/cosmicplayground', // TODO change to `cosmicplayground.org`
		title: '<a href="https://www.cosmicplayground.org">cosmicplayground.org</a>', // TODO @many this is a hack because cosmicplayground hasn't been deployed (remove glyph)
		subtitle: '<a class="chip" href="https://github.com/ryanatkn/cosmicplayground">source</a>',
		description: 'hobby project for fun and learning', // TODO @many this is a hack because cosmicplayground hasn't been deployed
		motto: 'tools and toys for expanding minds', // TODO @many this is a hack because cosmicplayground hasn't been deployed
		logo_style: 'border-radius: 50%',
		logo: 'favicon.png', // TODO @many this is a hack because cosmicplayground hasn't been deployed
	},
];

const projects: Array<ProjectInfo> = projects_metadata.map((project_metadata) => {
	const repo = repos_json.find((d) => {
		if (!('name' in d)) return false;
		return d.name === project_metadata.repo;
	});
	if (!repo) return project_metadata;
	const {
		description,
		homepage,
		motto,
		logo = project_metadata.logo, // TODO @many this is a hack because cosmicplayground hasn't been deployed
		logo_alt,
		glyph,
	} = repo.library_json.package_json;
	return {description, homepage, motto, logo, logo_alt, glyph, ...project_metadata};
});
