// generated by gitops_sync.task.js
import type {RepoJson} from '@ryanatkn/fuz_gitops/repo.svelte.js';

export const repos_json: Array<RepoJson> = JSON.parse(
	'[\
	{\
		"package_json": {\
			"name": "@ryanatkn/zzz",\
			"version": "0.0.1",\
			"description": "fullstack web toolkit for power users and devs",\
			"motto": "nice web things for the tired",\
			"glyph": "💤",\
			"logo": "logo.svg",\
			"logo_alt": "three sleepy z\'s",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://www.zzz.software/",\
			"repository": "https://github.com/ryanatkn/zzz",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"bugs": "https://github.com/ryanatkn/zzz/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"typecheck": "gro typecheck",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy",\
				"serve": "gro build && npm run preview & node dist_server/server/server.js"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"peerDependencies": {\
				"@sveltejs/kit": "^2",\
				"svelte": "^5"\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz": "^0.163.0",\
				"@ryanatkn/gro": "^0.177.1",\
				"@ryanatkn/moss": "^0.39.0",\
				"@sveltejs/adapter-node": "^5.4.0",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/package": "^2.5.6",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"@types/node": "^24.10.1",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"jsdom": "^27.2.0",\
				"ollama": "^0.6.3",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.44.0",\
				"svelte-check": "^4.3.4",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.48.0",\
				"vitest": "^4.0.13",\
				"zod": "^4.1.13"\
			},\
			"dependencies": {\
				"@anthropic-ai/sdk": "^0.71.0",\
				"@google/generative-ai": "^0.24.1",\
				"@hono/node-server": "^1.19.6",\
				"@hono/node-ws": "^1.2.0",\
				"@ryanatkn/belt": "^0.39.0",\
				"date-fns": "^4.1.0",\
				"esm-env": "^1.2.2",\
				"hono": "^4.10.6",\
				"openai": "^6.9.1"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.ts": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.svelte": {\
					"types": "./dist/*.svelte.d.ts",\
					"svelte": "./dist/*.svelte",\
					"default": "./dist/*.svelte"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/zzz",\
			"version": "0.0.1",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "in_progress",\
			"conclusion": null\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/moss",\
			"version": "0.39.0",\
			"description": "CSS framework and design system",\
			"motto": "magical organic stylesheets",\
			"glyph": "🌿",\
			"logo": "logo.svg",\
			"logo_alt": "a fuzzy tuft of green moss",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://moss.ryanatkn.com/",\
			"repository": "https://github.com/ryanatkn/moss",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"bugs": "https://github.com/ryanatkn/moss/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/belt": "^0.39.0",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz": "^0.162.1",\
				"@ryanatkn/fuz_code": "^0.36.0",\
				"@ryanatkn/gro": "^0.177.1",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/package": "^2.5.6",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"@types/node": "^24.10.1",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.44.0",\
				"svelte-check": "^4.3.4",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.48.0",\
				"vitest": "^4.0.13",\
				"zod": "^4.1.13"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.ts": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.css": {\
					"default": "./dist/*.css"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/moss",\
			"version": "0.39.0",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz",\
			"version": "0.163.0",\
			"description": "Svelte UI library",\
			"motto": "friendly user zystem",\
			"glyph": "🧶",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly brown spider facing you",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://www.fuz.dev/",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"repository": {\
				"type": "git",\
				"url": "git+https://github.com/ryanatkn/fuz.git"\
			},\
			"bugs": "https://github.com/ryanatkn/fuz/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"peerDependencies": {\
				"@ryanatkn/belt": ">=0.39.0",\
				"@ryanatkn/fuz_code": ">=0.36.0",\
				"@ryanatkn/gro": ">=0.177.0",\
				"@ryanatkn/moss": ">=0.39.0",\
				"@sveltejs/kit": "^2.47.3",\
				"esm-env": "^1",\
				"svelte": "^5",\
				"svelte2tsx": "^0.7.45",\
				"zod": "^4.1.12"\
			},\
			"peerDependenciesMeta": {\
				"@ryanatkn/fuz_code": {\
					"optional": true\
				},\
				"@ryanatkn/gro": {\
					"optional": true\
				},\
				"esm-env": {\
					"optional": true\
				}\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/belt": "^0.39.0",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz_code": "^0.36.0",\
				"@ryanatkn/gro": "^0.177.1",\
				"@ryanatkn/moss": "^0.39.0",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/package": "^2.5.6",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"@types/node": "^24.10.1",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"esm-env": "^1.2.2",\
				"jsdom": "^27.2.0",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.43.14",\
				"svelte-check": "^4.3.4",\
				"svelte2tsx": "^0.7.45",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.47.0",\
				"vitest": "^4.0.13",\
				"zod": "^4.1.13"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.ts": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.svelte": {\
					"types": "./dist/*.svelte.d.ts",\
					"svelte": "./dist/*.svelte",\
					"default": "./dist/*.svelte"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz",\
			"version": "0.163.0",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": [\
			{\
				"number": 71,\
				"title": "use the `dialog` element in `Dialog`",\
				"user": {\
					"login": "ryanatkn"\
				},\
				"draft": true\
			}\
		]\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/gro",\
			"version": "0.177.1",\
			"description": "task runner and toolkit extending SvelteKit",\
			"motto": "generate, run, optimize",\
			"glyph": "🌰",\
			"logo": "logo.svg",\
			"logo_alt": "a pixelated green oak acorn with a glint of sun",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://gro.ryanatkn.com/",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"repository": {\
				"type": "git",\
				"url": "git+https://github.com/ryanatkn/gro.git"\
			},\
			"bugs": "https://github.com/ryanatkn/gro/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"bootstrap": "rm -rf .gro dist && svelte-kit sync && svelte-package && chmod +x ./dist/gro.js && npm link -f",\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"bin": {\
				"gro": "dist/gro.js"\
			},\
			"keywords": [\
				"web",\
				"tools",\
				"task runner",\
				"tasks",\
				"codegen",\
				"svelte",\
				"sveltekit",\
				"vite",\
				"typescript"\
			],\
			"dependencies": {\
				"chokidar": "^4.0.3",\
				"dotenv": "^17.2.3",\
				"esm-env": "^1.2.2",\
				"mri": "^1.2.0",\
				"oxc-parser": "^0.99.0",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"ts-blank-space": "^0.6.2",\
				"tslib": "^2.8.1",\
				"zod": "^4.1.13"\
			},\
			"peerDependencies": {\
				"@ryanatkn/belt": ">=0.39.0",\
				"@sveltejs/kit": "^2",\
				"esbuild": "^0.27.0",\
				"svelte": "^5",\
				"typescript": "^5",\
				"vitest": "^3 || ^4"\
			},\
			"peerDependenciesMeta": {\
				"@sveltejs/kit": {\
					"optional": true\
				},\
				"vitest": {\
					"optional": true\
				}\
			},\
			"optionalDependencies": {\
				"vitest": "^3 || ^4"\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@changesets/types": "^6.1.0",\
				"@ryanatkn/belt": "^0.39.0",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz": "^0.162.0",\
				"@ryanatkn/fuz_code": "^0.36.0",\
				"@ryanatkn/moss": "^0.39.0",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/package": "^2.5.6",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"@types/node": "^24.10.1",\
				"esbuild": "^0.27.0",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"svelte": "^5.44.0",\
				"svelte-check": "^4.3.4",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.48.0",\
				"vitest": "^4.0.13"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				".": {\
					"types": "./dist/index.d.ts",\
					"default": "./dist/index.js"\
				},\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.ts": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/gro",\
			"version": "0.177.1",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/belt",\
			"version": "0.39.0",\
			"description": "utility belt for JS",\
			"glyph": "🦕",\
			"logo": "logo.svg",\
			"logo_alt": "a green sauropod wearing a brown utility belt",\
			"motto": "ancient not extinct",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://belt.ryanatkn.com/",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"repository": {\
				"type": "git",\
				"url": "git+https://github.com/ryanatkn/belt.git"\
			},\
			"bugs": "https://github.com/ryanatkn/belt/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy",\
				"benchmark": "gro run src/benchmarks/slugify_benchmark.ts",\
				"benchmark-deep-equal": "node --max-old-space-size=8192 --expose-gc --import @ryanatkn/gro/register.js src/lib/deep_equal.bench_comparison.ts",\
				"benchmark-deep-equal-deno": "deno run --allow-read --allow-env --v8-flags=--expose-gc src/lib/deep_equal.bench_comparison.ts"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"keywords": [\
				"js",\
				"typescript",\
				"utilities",\
				"web"\
			],\
			"peerDependencies": {\
				"@types/node": "^24",\
				"esm-env": "^1.2.2",\
				"zod": "^4.0.14"\
			},\
			"peerDependenciesMeta": {\
				"@types/node": {\
					"optional": true\
				},\
				"esm-env": {\
					"optional": true\
				},\
				"zod": {\
					"optional": true\
				}\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz": "^0.161.1",\
				"@ryanatkn/fuz_code": "^0.34.0",\
				"@ryanatkn/gro": "^0.175.0",\
				"@ryanatkn/moss": "^0.38.0",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/package": "^2.5.6",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"@types/node": "^24.10.1",\
				"dequal": "^2.0.3",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"esm-env": "^1.2.2",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.43.14",\
				"svelte-check": "^4.3.4",\
				"tinybench": "^5.1.0",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.47.0",\
				"vitest": "^4.0.13",\
				"zod": "^4.1.12"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.ts": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/belt",\
			"version": "0.39.0",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "failure"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz_template",\
			"version": "0.0.1",\
			"description": "a static web app and Node library template with TypeScript, Svelte, SvelteKit, Vite, esbuild, Gro, and Fuz",\
			"glyph": "❄",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly pixelated spider facing you",\
			"public": true,\
			"homepage": "https://template.fuz.dev/",\
			"repository": "https://github.com/ryanatkn/fuz_template",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"devDependencies": {\
				"@ryanatkn/belt": "^0.39.0",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz": "^0.162.0",\
				"@ryanatkn/gro": "^0.177.1",\
				"@ryanatkn/moss": "^0.39.0",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.44.0",\
				"svelte-check": "^4.3.4",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.48.0",\
				"vitest": "^4.0.13"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist"\
			]\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz_template",\
			"version": "0.0.1",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz_blog",\
			"version": "0.18.0",\
			"description": "blog software from scratch with SvelteKit",\
			"glyph": "🖊️",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly yellow spider facing you",\
			"public": true,\
			"homepage": "https://blog.fuz.dev/",\
			"repository": "https://github.com/ryanatkn/fuz_blog",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"peerDependencies": {\
				"@ryanatkn/belt": ">=0.39.0",\
				"@ryanatkn/fuz": ">=0.162.0",\
				"@ryanatkn/fuz_mastodon": ">=0.35.0",\
				"@ryanatkn/gro": ">=0.177.1",\
				"@ryanatkn/moss": ">=0.39.0",\
				"@sveltejs/kit": "^2",\
				"date-fns": "^4",\
				"svelte": "^5"\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/belt": "^0.39.0",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz": "^0.162.0",\
				"@ryanatkn/fuz_code": "^0.36.0",\
				"@ryanatkn/fuz_mastodon": "^0.36.0",\
				"@ryanatkn/gro": "^0.177.1",\
				"@ryanatkn/moss": "^0.39.0",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/package": "^2.5.6",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"@types/node": "^24.10.1",\
				"date-fns": "^4.1.0",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.44.0",\
				"svelte-check": "^4.3.4",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.48.0",\
				"vitest": "^4.0.13"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.ts": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.svelte": {\
					"types": "./dist/*.svelte.d.ts",\
					"svelte": "./dist/*.svelte",\
					"default": "./dist/*.svelte"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz_blog",\
			"version": "0.18.0",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz_mastodon",\
			"version": "0.36.0",\
			"description": "Mastodon components and helpers for Svelte, SvelteKit, and Fuz",\
			"glyph": "🦣",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly purple spider facing you",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://mastodon.fuz.dev/",\
			"repository": "https://github.com/ryanatkn/fuz_mastodon",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"bugs": "https://github.com/ryanatkn/fuz_mastodon/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"peerDependencies": {\
				"@ryanatkn/belt": ">=0.39.0",\
				"@ryanatkn/fuz": ">=0.162.0",\
				"@ryanatkn/moss": ">=0.39.0",\
				"@sveltejs/kit": "^2",\
				"date-fns": "^4",\
				"esm-env": "^1",\
				"svelte": "^5"\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/belt": "^0.39.0",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz": "^0.162.0",\
				"@ryanatkn/fuz_code": "^0.36.0",\
				"@ryanatkn/gro": "^0.177.1",\
				"@ryanatkn/moss": "^0.39.0",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/package": "^2.5.6",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"date-fns": "^4.1.0",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"esm-env": "^1.2.2",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.44.0",\
				"svelte-check": "^4.3.4",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.48.0",\
				"vitest": "^4.0.13"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.ts": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.svelte": {\
					"types": "./dist/*.svelte.d.ts",\
					"svelte": "./dist/*.svelte",\
					"default": "./dist/*.svelte"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz_mastodon",\
			"version": "0.36.0",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz_code",\
			"version": "0.36.0",\
			"description": "syntax styling utilities and components for TypeScript, Svelte, and Markdown",\
			"glyph": "🎨",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly pink spider facing you",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://code.fuz.dev/",\
			"repository": "https://github.com/ryanatkn/fuz_code",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"bugs": "https://github.com/ryanatkn/fuz_code/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy",\
				"benchmark": "gro run benchmark/run_benchmarks.ts",\
				"benchmark-compare": "gro run benchmark/compare/run_compare.ts",\
				"update-generated-fixtures": "gro src/test/fixtures/update"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"peerDependencies": {\
				"@ryanatkn/moss": ">=0.39.0",\
				"svelte": "^5"\
			},\
			"peerDependenciesMeta": {\
				"@ryanatkn/moss": {\
					"optional": true\
				},\
				"svelte": {\
					"optional": true\
				}\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/belt": "^0.39.0",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz": "^0.162.1",\
				"@ryanatkn/gro": "^0.177.1",\
				"@ryanatkn/moss": "^0.39.0",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/package": "^2.5.6",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"@types/node": "^24.10.1",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"esm-env": "^1.2.2",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.44.0",\
				"svelte-check": "^4.3.4",\
				"tinybench": "^5.1.0",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.48.0",\
				"vitest": "^4.0.13"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.ts": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.svelte": {\
					"types": "./dist/*.svelte.d.ts",\
					"svelte": "./dist/*.svelte",\
					"default": "./dist/*.svelte"\
				},\
				"./*.css": {\
					"default": "./dist/*.css"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz_code",\
			"version": "0.36.0",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "webdevladder.net",\
			"version": "0.0.1",\
			"description": "a YouTube channel and blog for realworld webdev with TypeScript and Svelte",\
			"motto": "up ↗",\
			"glyph": "🪜",\
			"logo": "logo.svg",\
			"logo_alt": "a spider web between two rungs of a ladder",\
			"license": "MIT",\
			"public": true,\
			"homepage": "https://www.webdevladder.net/",\
			"repository": "https://github.com/ryanatkn/webdevladder.net",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"bugs": "https://github.com/ryanatkn/webdevladder.net/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"devDependencies": {\
				"@ryanatkn/belt": "^0.39.0",\
				"@ryanatkn/eslint-config": "^0.9.0",\
				"@ryanatkn/fuz": "^0.162.0",\
				"@ryanatkn/fuz_blog": "^0.18.0",\
				"@ryanatkn/fuz_code": "^0.36.0",\
				"@ryanatkn/fuz_mastodon": "^0.36.0",\
				"@ryanatkn/gro": "^0.177.1",\
				"@ryanatkn/moss": "^0.39.0",\
				"@sveltejs/adapter-static": "^3.0.10",\
				"@sveltejs/kit": "^2.49.0",\
				"@sveltejs/vite-plugin-svelte": "^6.2.1",\
				"eslint": "^9.39.1",\
				"eslint-plugin-svelte": "^3.13.0",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.44.0",\
				"svelte-check": "^4.3.4",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.3",\
				"typescript-eslint": "^8.48.0",\
				"vitest": "^4.0.13"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist"\
			]\
		},\
		"src_json": {\
			"name": "webdevladder.net",\
			"version": "0.0.1",\
			"modules": []\
		},\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	}\
]',
);
