// generated by gitops_sync.task.js - do not edit

import type {RepoJson} from '@fuzdev/fuz_gitops/repo.svelte.js';

import json from './repos.json' with {type: 'json'};

export const repos_json: Array<RepoJson> = json as unknown as Array<RepoJson>;
